version: '3.8'

services:
  api:
    build: .
    ports:
      - "8000:8000"
    environment:
      - PROJECT_NAME=${PROJECT_NAME:-POI-Backend}
      - API_VERSION=${API_VERSION:-1.0.0}
      - ALLOW_ORIGINS=${ALLOW_ORIGINS:-*}
      - MAX_FILE_SIZE_MB=${MAX_FILE_SIZE_MB:-10}
      - MAX_POI_PER_FILE=${MAX_POI_PER_FILE:-10000}
      - DEFAULT_SEARCH_RADIUS_M=${DEFAULT_SEARCH_RADIUS_M:-1000}
      - MAX_SEARCH_RADIUS_M=${MAX_SEARCH_RADIUS_M:-50000}
    volumes:
      - ./app:/app/app  # For development hot reload
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload